name: "Issue Form: Bug Report"
description: "Create a report to help us improve"
title: "BUG - "
labels: ["bug-priority:medium", "bug-status:new", "type:bug"]
assignees:
  - ''
body:
  # Source
  - type: markdown
    attributes:
      value: |
          ##
          *Note: Please check if the issue has already been reported before proceeding. This can avoid creating and handling duplicates, saving you and your colleagues time.*
          
          #### Source
          - Please add a relevant source link to help development team identify source of the issue
          - Please review the labels once bug is created. Double check the source labels: https://github.wdf.sap.corp/ux-engineering/tools-suite/labels?q=source

  - type: dropdown
    id: source_type
    attributes:
      label: What led to this issue?
      multiple: true
      options:
        - User Story
        - Technical Backlog Item
        - Customer Case
        - Internal Tncident
        - E2E Test
        - Other

  - type: input
    id: source_link
    attributes:
      label: "Source link"
      placeholder: "Paste source link here..."

  - type: markdown
    attributes:
      value: "---"

  # Description
  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: "Document some details about the bug..."

  # Steps to Reproduce
  - type: textarea
    id: reproduce_steps 
    attributes:
      label: Steps to reproduce
      description: Provide clear steps to reproduce the issue.
      placeholder: |
        1. Go to '...'.
        2.
        3.
  
  # Expected results
  - type: textarea
    id: expected_results
    attributes:
      label: "Expected results"
  
  # Actual results
  - type: textarea
    id: actual_results
    attributes:
      label: "Actual results"

   # Screenshots
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
      placeholder: "Drag & drop an image here or copy-paste a screenshot."
  
  # Fiori component/version
  - type: markdown
    attributes:
      value: |
          ##
          #### Fiori tools component/version
          - Run command `Fiori: Open Environment Check`, select `Gather Development Environment Information` and `View results`
          - Please review the labels once bug is created. Double check the source labels: https://github.wdf.sap.corp/ux-engineering/tools-suite/labels?q=source

  - type: input
    id: fiori_component
    attributes:
      label: "Add fiori tools component/version"
      placeholder: "Copy and paste here the section 'Environment' from generated .md file"

  # Project files
  - type: textarea
    id: project_files
    attributes:
      label: "Project Files"
      description: |
        Run command `Fiori: Archive Project`, to attach your project if you determine it will be helpful for development team.

  # Operating System
  - type: dropdown
    id: operating_system
    attributes:
      label: Operating System
      multiple: true
      options:
        - Mac OS
        - Windows

  # Browser
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  # Environment
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      multiple: true
      options:
        - Master
        - Staging
        - Production
  
  # Root Cause Analysis
  - type: markdown
    attributes:
      value: |
          #### Root Cause Analysis
          *Note: Please check if the issue has already been reported before proceeding. This save you and colleagues time to create and handle duplicates.*


  - type: textarea
    id: rca_problem
    attributes:
      label: "Problem"
      description: "Describe the problem"

  - type: textarea
    id: rca_fix
    attributes:
      label: "Fix"
      description: "Describe the fix"
  
  - type: textarea
    id: rca_why_missed
    attributes:
      label: "Why was it missed?"
      description: "Some explanation why this issue was missed during normal development/testing cycle"

  - type: textarea
    id: rca_avoid
    attributes:
      label: "How can we avoid this"
      description: "If we don't want to see this type of issue anymore, what we should do to prevent it?"